version: "3.9"
services:
  snowflake:
    container_name: snowflake
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
